# Change these first
owner: beaini # Your GitHub username
repo: upptimeA # Your GitHub repository name

# Add your sites here
sites:
  - name: Cryptolens - Home
    url: cryptolens.ca/
    maxResponseTime: 1000
    assignees:
      - mayabeaini
      - beaini
  - name: Cryptolens - API
    url: api.cryptolens.ca/api/pipeline_calculation?amount=10000&symbol=BTC_CAD&side=BUY
    maxResponseTime: 1000
    assignees:
      - mayabeaini
      - beaini

status-website:
  baseUrl: /repo # where "repo" is your repository name
  name: Your Status Website

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/15 * * * *"
  
